# Generated by Django 5.1.6 on 2025-02-13 08:32

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('inn', models.CharField(max_length=16)),
                ('kpp', models.CharField(max_length=9)),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True)),
                ('bic', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'companies',
                'db_table_comment': '╥рсышЎр ё ъюьярэш\xa0ьш',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FunctionsDict',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('version', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'functions_dict',
                'db_table_comment': '╥рсышЎр ёяЁртюўэшъ Ёюыхт√ї ЇєэъЎшщ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'modules',
                'db_table_comment': '╥рсышЎр фюяюыэшЄхы№э√ї ьюфєыхщ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyCodeDict',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'property_code_dict',
                'db_table_comment': '╥рсышЎр ёяЁртюўэшъ ъюфют фы\xa0 ётющёЄт яюы№чютрЄхы\xa0\nPROFILE_IMAGE - яєЄ№ фю ърЁЄшэъш ё яЁюЇшыхь яюы№чютрЄхы\xa0\nUSER_MOBILE - ЄхыхЇюэ яюы№чютрЄхы\xa0\nUSER_NUMVER - шэфш√шфєры№э√щ эюьхЁ яюы№чютрЄхы\xa0',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'reports',
                'db_table_comment': '╥рсышЎр ёяЁртюўэшъ юЄўхЄют',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolesDict',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'roles_dict',
                'db_table_comment': '╥рсышЎр ёяЁртюўэшъ Ёюыхщ яюы№чютрЄхы\xa0',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SettingsDict',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'settings_dict',
                'db_table_comment': '╥рсышЎр ёяЁртюўэшъ ъюфют ёшёЄхь√',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShablonDict',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shablon_dict',
                'db_table_comment': '╥рсышЎш ёяЁртюўэшъ °рсыюэют',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusDict',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'status_dict',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimezoneDict',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('timezone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timezone_dict',
                'db_table_comment': '╥рсышЎр ё ёяЁртўюэшъ Єрщьчюэ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.companies')),
            ],
            options={
                'db_table': 'departments',
                'db_table_comment': '╥рсышЎр ё яюфЁрчфыхэшщ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lisense_key', models.CharField(max_length=1000)),
                ('active_from', models.DateField()),
                ('active_to', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.companies')),
            ],
            options={
                'db_table': 'license',
                'db_table_comment': '╥рсышЎр ё ышЎхэчш\xa0ьш',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuleCompanyLinks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('active_from', models.DateField()),
                ('active_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.companies')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.modules')),
            ],
            options={
                'db_table': 'module_company_links',
                'db_table_comment': '╥рсышЎр ёт\xa0чхщ ьюфєыхщ ш ъюьярэшщ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyProperties',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.companies')),
                ('property_code', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.propertycodedict')),
            ],
            options={
                'db_table': 'company_properties',
                'db_table_comment': '╥рсышЎр ётющёЄт ъюьярэшщ',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.propertycodedict'),
        ),
        migrations.CreateModel(
            name='RoleFunctions',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('function_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.functionsdict')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.rolesdict')),
            ],
            options={
                'db_table': 'role_functions',
                'db_table_comment': '╥рсышЎр ё Ёюыхт√ьш ЇєэъЎш\xa0ьш',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('active_from', models.DateField()),
                ('active_to', models.DateField(blank=True, null=True)),
                ('setting_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.settingsdict')),
            ],
            options={
                'db_table': 'settings',
                'db_table_comment': '╥рсышЎр юс∙шї ётющёЄ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.companies')),
            ],
            options={
                'db_table': 'user_groups',
                'db_table_comment': '╥рсышЎр уЁєяя яюы№чютрЄхыхщ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('firtsname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('patronymic', models.CharField(blank=True, max_length=60, null=True)),
                ('created_date', models.DateField()),
                ('user_lock', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.companies')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usergroups')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('timezone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.timezonedict')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': '╥рсышЎр яюы№чютрЄхыхщ',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active_from', models.DateField()),
                ('active_to', models.DateField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.rolesdict')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
            ],
            options={
                'db_table': 'user_roles',
                'db_table_comment': '╥рсышЎр Ёюыхщ яюы№чютрЄхыхщ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserReportLinks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('acive_from', models.DateField()),
                ('active_to', models.DateField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.reports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
            ],
            options={
                'db_table': 'user_report_links',
                'db_table_comment': '╥рсышЎр ёт\xa0чхщ юЄўхЄют ш яюы№чютрЄхыхщ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('property_code', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.propertycodedict')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
            ],
            options={
                'db_table': 'user_properties',
                'db_table_comment': '╥рсышЎр ётющёЄт яюы№чютрЄхыхщ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSendings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('message', models.CharField(max_length=4000)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.statusdict')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
            ],
            options={
                'db_table': 'user_sendings',
                'db_table_comment': '╥рсышЎр Ёрёё√ыъш ёююс∙хэшщ яю яюы№чютрЄхы\xa0ь',
                'managed': True,
            },
        ),
    ]
