# Generated by Django 5.1.6 on 2025-02-14 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='usergroups',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.companies', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='usergroups',
            name='group_name',
            field=models.CharField(max_length=255, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.rolesdict', verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
