# Generated by Django 5.1.6 on 2025-02-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_rolesdict_code_alter_rolesdict_name'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='companies',
            table_comment='Таблица с компаниями',
        ),
        migrations.AlterModelTableComment(
            name='companyproperties',
            table_comment='Таблица свойств компаний',
        ),
        migrations.AlterModelTableComment(
            name='departments',
            table_comment='Таблица с подраздлений',
        ),
        migrations.AlterModelTableComment(
            name='functionsdict',
            table_comment='Таблица справочник ролевых функций',
        ),
        migrations.AlterModelTableComment(
            name='license',
            table_comment='Таблица с лицензиями',
        ),
        migrations.AlterModelTableComment(
            name='modulecompanylinks',
            table_comment='Таблица связей модулей и компаний',
        ),
        migrations.AlterModelTableComment(
            name='modules',
            table_comment='Таблица дополнительных модулей',
        ),
        migrations.AlterModelTableComment(
            name='propertycodedict',
            table_comment='Таблица справочник кодов для свойств пользователя\nPROFILE_IMAGE - путь до картинки с профилем пользователя\nUSER_MOBILE - телефон пользователя\nUSER_NUMVER - индиыидуальный номер пользователя',
        ),
        migrations.AlterModelTableComment(
            name='reports',
            table_comment='Таблица справочник отчетов',
        ),
        migrations.AlterModelTableComment(
            name='rolefunctions',
            table_comment='Таблица с ролевыми функциями',
        ),
        migrations.AlterModelTableComment(
            name='rolesdict',
            table_comment='Таблица справочник ролей пользователя',
        ),
        migrations.AlterModelTableComment(
            name='settings',
            table_comment='Таблица общих свойст',
        ),
        migrations.AlterModelTableComment(
            name='settingsdict',
            table_comment='Таблица справочник кодов системы',
        ),
        migrations.AlterModelTableComment(
            name='shablondict',
            table_comment='Таблици справочник шаблонов',
        ),
        migrations.AlterModelTableComment(
            name='timezonedict',
            table_comment='Таблица с справчоник таймзон',
        ),
        migrations.AlterModelTableComment(
            name='usergroups',
            table_comment='Таблица групп пользователей',
        ),
        migrations.AlterModelTableComment(
            name='userproperties',
            table_comment='Таблица свойств пользователей',
        ),
        migrations.AlterModelTableComment(
            name='userreportlinks',
            table_comment='Таблица связей отчетов и пользователей',
        ),
        migrations.AlterModelTableComment(
            name='userroles',
            table_comment='Таблица ролей пользователей',
        ),
        migrations.AlterModelTableComment(
            name='users',
            table_comment='Таблица пользователей',
        ),
        migrations.AlterModelTableComment(
            name='usersendings',
            table_comment='Таблица рассылки сообщений по пользователям',
        ),
        migrations.AlterField(
            model_name='rolesdict',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Код роли'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
