# Generated by Django 5.1.6 on 2025-02-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_companies_table_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firtsname',
            new_name='firstname',
        ),
    ]
