# Generated by Django 5.1.6 on 2025-02-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_firtsname_users_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionsdict',
            name='version',
            field=models.SmallIntegerField(default=0),
        ),
    ]
