# Generated by Django 5.1.6 on 2025-02-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_modules_id_alter_reports_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='active_from',
            field=models.DateField(auto_now=True),
        ),
    ]
