# Generated by Django 5.1.6 on 2025-02-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userroles_active_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
