# Generated by Django 5.1.6 on 2025-02-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_users_date_joined_remove_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='bic',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='inn',
            field=models.CharField(max_length=16, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='kpp',
            field=models.CharField(max_length=9, unique=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='functionsdict',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='functionsdict',
            name='version',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
    ]
