# Generated by Django 5.1.6 on 2025-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_companies_bic_alter_companies_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionsdict',
            name='version',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
