# Generated by Django 5.1.6 on 2025-02-17 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_functionsdict_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.propertycodedict', verbose_name='Свойства'),
        ),
        migrations.AlterField(
            model_name='companyproperties',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies'),
        ),
        migrations.AlterField(
            model_name='companyproperties',
            name='property_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.propertycodedict'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies'),
        ),
        migrations.AlterField(
            model_name='license',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies'),
        ),
        migrations.AlterField(
            model_name='modulecompanylinks',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies'),
        ),
        migrations.AlterField(
            model_name='modulecompanylinks',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modules'),
        ),
        migrations.AlterField(
            model_name='rolefunctions',
            name='function_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.functionsdict'),
        ),
        migrations.AlterField(
            model_name='rolefunctions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rolesdict'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='setting_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.settingsdict'),
        ),
        migrations.AlterField(
            model_name='usergroups',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='property_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.propertycodedict'),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreportlinks',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reports'),
        ),
        migrations.AlterField(
            model_name='userreportlinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rolesdict', verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.companies', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usergroups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='users',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.timezonedict', verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='usersendings',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statusdict'),
        ),
        migrations.AlterField(
            model_name='usersendings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
