# Generated by Django 5.1.6 on 2025-02-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0020_companies_idx_companies_inn_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='departments',
            name='idx_departments_company_id',
        ),
        migrations.RemoveIndex(
            model_name='usergroups',
            name='idx_user_groups_company_id',
        ),
        migrations.AddIndex(
            model_name='companyproperties',
            index=models.Index(fields=['company'], name='idx_comp_prop_comp_id'),
        ),
        migrations.AddIndex(
            model_name='companyproperties',
            index=models.Index(fields=['property_code'], name='idx_comp_prop_prop_code_id'),
        ),
        migrations.AddIndex(
            model_name='companyproperties',
            index=models.Index(fields=['company', 'property_code'], name='idx_c_proper_comp_prop'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['company', 'code'], name='idx_depart_comp_id_code'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['company', 'name'], name='idx_depart_comp_id_name'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['name'], name='idx_departments_name'),
        ),
        migrations.AddIndex(
            model_name='functionsdict',
            index=models.Index(fields=['code', 'version'], name='idx_func_dict_code_version'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['company'], name='idx_license_company_id'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['active_from'], name='idx_license_active_from'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['active_to'], name='idx_license_active_to'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['company', 'active_from'], name='idx_lic_comp_id_active_from'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['company', 'active_from', 'active_to'], name='idx_l_co_i_act_fr_act_to'),
        ),
        migrations.AddIndex(
            model_name='modulecompanylinks',
            index=models.Index(fields=['company'], name='idx_modul_comp_l_company_id'),
        ),
        migrations.AddIndex(
            model_name='modulecompanylinks',
            index=models.Index(fields=['module'], name='idx_modul_comp_l_module_id'),
        ),
        migrations.AddIndex(
            model_name='modulecompanylinks',
            index=models.Index(fields=['active_from'], name='idx_modul_comp_l_active_from'),
        ),
        migrations.AddIndex(
            model_name='modulecompanylinks',
            index=models.Index(fields=['active_to'], name='idx_modul_comp_l_active_to'),
        ),
        migrations.AddIndex(
            model_name='modulecompanylinks',
            index=models.Index(fields=['company', 'active_from', 'active_to'], name='idx_m_c_l_c_i_a_fr_active_to'),
        ),
        migrations.AddIndex(
            model_name='modulecompanylinks',
            index=models.Index(fields=['module', 'company'], name='idx_mod_com_l_mod_company'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['code'], name='idx_modules_code'),
        ),
        migrations.AddIndex(
            model_name='modules',
            index=models.Index(fields=['name'], name='idx_modules_name'),
        ),
        migrations.AddIndex(
            model_name='propertycodedict',
            index=models.Index(fields=['code'], name='idx_property_code_dict_code'),
        ),
        migrations.AddIndex(
            model_name='propertycodedict',
            index=models.Index(fields=['group_code', 'code'], name='idx_prop_cod_d_gr_co_code'),
        ),
        migrations.AddIndex(
            model_name='propertycodedict',
            index=models.Index(fields=['name'], name='idx_property_code_dict_name'),
        ),
        migrations.AddIndex(
            model_name='reports',
            index=models.Index(fields=['code'], name='idx_reports_code'),
        ),
        migrations.AddIndex(
            model_name='reports',
            index=models.Index(fields=['name'], name='idx_reports_name'),
        ),
        migrations.AddIndex(
            model_name='reports',
            index=models.Index(fields=['code', 'version'], name='idx_reports_code_version'),
        ),
        migrations.AddIndex(
            model_name='rolefunctions',
            index=models.Index(fields=['role'], name='idx_role_functions_role_id'),
        ),
        migrations.AddIndex(
            model_name='rolefunctions',
            index=models.Index(fields=['function_code'], name='idx_rol_func_func_cod_id'),
        ),
        migrations.AddIndex(
            model_name='rolefunctions',
            index=models.Index(fields=['role', 'function_code'], name='idx_role_functions_role_func'),
        ),
        migrations.AddIndex(
            model_name='rolesdict',
            index=models.Index(fields=['code'], name='idx_roles_dict_code'),
        ),
        migrations.AddIndex(
            model_name='rolesdict',
            index=models.Index(fields=['name'], name='idx_roles_dict_name'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['setting_code'], name='idx_settings_setting_code_id'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['active_from'], name='idx_settings_active_from'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['active_to'], name='idx_settings_active_to'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['active_from', 'active_to'], name='idx_sett_act_from_act_to'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['setting_code', 'active_from', 'active_to'], name='idx_set_set_c_id_act_fr_act_to'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['setting_code', 'active_to'], name='idx_set_set_code_id_act_to'),
        ),
        migrations.AddIndex(
            model_name='settingsdict',
            index=models.Index(fields=['code'], name='idx_settings_dict_code'),
        ),
        migrations.AddIndex(
            model_name='settingsdict',
            index=models.Index(fields=['name'], name='idx_settings_dict_name'),
        ),
        migrations.AddIndex(
            model_name='shablondict',
            index=models.Index(fields=['code'], name='idx_shablon_dict_code'),
        ),
        migrations.AddIndex(
            model_name='shablondict',
            index=models.Index(fields=['name'], name='idx_shablon_dict_name'),
        ),
        migrations.AddIndex(
            model_name='statusdict',
            index=models.Index(fields=['code'], name='idx_status_dict_code'),
        ),
        migrations.AddIndex(
            model_name='statusdict',
            index=models.Index(fields=['name'], name='idx_status_dict_name'),
        ),
        migrations.AddIndex(
            model_name='timezonedict',
            index=models.Index(fields=['timezone_name'], name='idx_timezone_dict_name'),
        ),
        migrations.AddIndex(
            model_name='timezonedict',
            index=models.Index(fields=['timezone'], name='idx_timezone_dict_timezone'),
        ),
        migrations.AddIndex(
            model_name='usergroups',
            index=models.Index(fields=['group_name'], name='idx_user_groups_group_name'),
        ),
        migrations.AddIndex(
            model_name='usergroups',
            index=models.Index(fields=['company', 'group_name'], name='idx_user_groups_company_group'),
        ),
        migrations.AddIndex(
            model_name='userproperties',
            index=models.Index(fields=['user'], name='idx_user_properties_user_id'),
        ),
        migrations.AddIndex(
            model_name='userproperties',
            index=models.Index(fields=['user', 'property_code'], name='id_us_prop_us_id_prop_cod_id'),
        ),
        migrations.AddIndex(
            model_name='userproperties',
            index=models.Index(fields=['property_code'], name='idx_us_prop_prop_code'),
        ),
        migrations.AddIndex(
            model_name='userreportlinks',
            index=models.Index(fields=['user'], name='id_us_rep_lin_user_id'),
        ),
        migrations.AddIndex(
            model_name='userreportlinks',
            index=models.Index(fields=['report'], name='id_us_rep_lin_report_id'),
        ),
        migrations.AddIndex(
            model_name='userreportlinks',
            index=models.Index(fields=['created_date'], name='id_us_rep_lin_created_date'),
        ),
        migrations.AddIndex(
            model_name='userreportlinks',
            index=models.Index(fields=['acive_from'], name='id_us_rep_lin_active_from'),
        ),
        migrations.AddIndex(
            model_name='userreportlinks',
            index=models.Index(fields=['active_to'], name='id_us_rep_lin_active_to'),
        ),
        migrations.AddIndex(
            model_name='userreportlinks',
            index=models.Index(fields=['user', 'report'], name='id_us_rep_lin_user_report'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['firstname'], name='idx_users_firstname'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['lastname'], name='idx_users_lastname'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['firstname', 'lastname'], name='idx_users_fullname'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['user_lock'], name='idx_users_user_lock'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['company', 'user_lock'], name='idx_users_company_lock_status'),
        ),
        migrations.AddIndex(
            model_name='usersendings',
            index=models.Index(fields=['user'], name='idx_user_sendings_user_id'),
        ),
        migrations.AddIndex(
            model_name='usersendings',
            index=models.Index(fields=['status'], name='idx_user_sendings_status_id'),
        ),
        migrations.AddIndex(
            model_name='usersendings',
            index=models.Index(fields=['created_date'], name='idx_user_sendings_created_date'),
        ),
        migrations.AddIndex(
            model_name='usersendings',
            index=models.Index(fields=['user', 'status'], name='idx_user_sendings_user_status'),
        ),
        migrations.AddConstraint(
            model_name='companies',
            constraint=models.UniqueConstraint(fields=('inn',), name='companies_inn_unique'),
        ),
        migrations.AddConstraint(
            model_name='companies',
            constraint=models.UniqueConstraint(fields=('kpp',), name='companies_kpp_unique'),
        ),
        migrations.AddConstraint(
            model_name='companies',
            constraint=models.UniqueConstraint(fields=('ogrn',), name='companies_ogrn_unique'),
        ),
        migrations.AddConstraint(
            model_name='companies',
            constraint=models.UniqueConstraint(fields=('bic',), name='companies_bic_unique'),
        ),
        migrations.AddConstraint(
            model_name='departments',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='departments_company_id_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='propertycodedict',
            constraint=models.UniqueConstraint(fields=('group_code', 'code'), name='property_code_dict_group_code_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='userproperties',
            constraint=models.UniqueConstraint(fields=('property_code',), name='user_properties_property_code_id_unique'),
        ),
    ]
