# Generated by Django 5.1.6 on 2025-02-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='bic',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='inn',
            field=models.CharField(max_length=16, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='kpp',
            field=models.CharField(max_length=9, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='users',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.companies', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='users',
            name='firtsname',
            field=models.CharField(max_length=60, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usergroups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(max_length=60, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='patronymic',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.timezonedict', verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_lock',
            field=models.BooleanField(default=False, verbose_name='Блокировка пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=60, verbose_name='Логин'),
        ),
    ]
