# Generated by Django 5.1.6 on 2025-02-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_companies_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'managed': True, 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
