# Generated by Django 5.1.6 on 2025-02-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=60, unique=True, verbose_name='Логин'),
        ),
    ]
