# Generated by Django 5.1.6 on 2025-02-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usergroups_comment_alter_usergroups_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesdict',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Код группы'),
        ),
        migrations.AlterField(
            model_name='rolesdict',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Имя роли'),
        ),
    ]
