# Generated by Django 5.1.6 on 2025-02-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_rolesdict_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesdict',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Права роли'),
        ),
        migrations.AlterField(
            model_name='rolesdict',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Имя роли'),
        ),
    ]
